<?php /** @var $this Meanbee_InfiniteScroll_Block_Script */ ?>
<?php if ($this->isScrollablePage()): ?>
    <script type="text/javascript">

        document.observe("dom:loaded", function() {
            new Meanbee_InfiniteScroll({
                pager_selector: '<?php echo $this->getPagerSelector() ?>',
                top_toolbar_selector: '<?php echo $this->getTopToolbarSelector() ?>',
                bottom_toolbar_selector: '<?php echo $this->getBottomToolbarSelector() ?>',
                button_selector: '<?php echo $this->getButtonSelector() ?>',
                busy_selector: '<?php echo $this->getBusySelector() ?>',

                showall_enabled: <?php echo ($this->isShowAllEnabled()) ? 'true' : 'false' ?>,
                showall_link: '<?php echo $this->getShowAllUrl() ?>',
                showall_text: 'Show all products',

                endpoint: '<?php echo $this->getEndpoint() ?>',
                request_parameters: <?php echo $this->getRequestParametersJson() ?>,

                autoscroll_enabled: <?php echo $this->isAutoscrollEnabled() ? 'true' : 'false' ?>,
                scroll_distance: <?php echo $this->getScrollDistance() ?>,

                display_mode: '<?php echo $this->getCategoryDisplayMode() ?>',

                grid_item_selector: '<?php echo $this->getGridItemSelector() ?>',
                grid_container_selector: '<?php echo $this->getGridContainerSelector() ?>',
                grid_container_action: '<?php echo $this->getGridContainerAction() ?>',

                list_item_selector: '<?php echo $this->getListItemSelector() ?>',
                list_container_selector: '<?php echo $this->getListContainerSelector() ?>',
                list_container_action: '<?php echo $this->getListContainerAction() ?>',

                on_last_page: <?php echo (!$this->hasMorePages()) ? 'true' : 'false' ?>,
                cookie_key: '<?php echo $this->getCookieKey() ?>'
            }, new Meanbee_InfiniteScroll_Cache(<?php echo Meanbee_InfiniteScroll_Helper_Cache::CACHE_LIFETIME ?>));
        });

    </script>

    <?php if ($this->hasMorePages() && !$this->isAutoscrollEnabled()): ?>
        <button class="meanbee-infinitescroll-button button"><span><span>Advance Infinite Scroll</span></span></button>
    <?php endif ?>

    <div class="meanbee-infinitescroll-busy" style="display: none"><img src="<?php echo $this->getSkinUrl('meanbee/infinitescroll/images/ajax_busy.gif') ?>" alt="Loading.." title="Loading.." /></div>

<?php else: ?>

    <!-- Meanbee/InfiniteScroll: This page isn't scrollable -->

<?php endif ?>